description: TEMPO
model_id: TEMPO_checkpoints/TEMPO-80M_v1
checkpoints: ./checkpoints/
task_name: long_term_forecast
prompt: 1
num_nodes: 1
seq_len: 336
pred_len: 96
label_len: 96
decay_fac: 0.5
learning_rate: 0.001
batch_size: 256
num_workers: 0
train_epochs: 10
lradj: type3
patience: 5
gpt_layers: 6
is_gpt: 1
e_layers: 3
d_model: 768
n_heads: 4
d_ff: 768
dropout: 0.3
enc_in: 7
c_out: 1
patch_size: 16
kernel_size: 25
loss_func: mse
pretrain: 0
freeze: 1
model: TEMPO
stride: 8
max_len: -1
hid_dim: 16
tmax: 20
itr: 3
cos: 1
equal: 1
pool: false
no_stl_loss: false
stl_weight: 0.001
config_path: ./configs/custom_dataset.yml
datasets: ETTm1,ETTh1,ETTm2,electricity,traffic,weather
target_data: Custom
use_token: 0
electri_multiplier: 1
traffic_multiplier: 1
embed: timeF
percent: 100
